// Compiles data/logos/*.json into src/logos.js. Run with: npm run logos
//
// Each JSON file: { key, name, kind, viewBox, paths: [{ d, fillRule }],
// source, license, trademark }. The viewBox is recomputed as the tight
// bounding box of the paths so every logo sizes consistently.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { svgPathBbox } from 'svg-path-bbox';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'data', 'logos');
const logos = {};
const credits = [];

for (const file of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
  const logo = JSON.parse(readFileSync(join(dir, file), 'utf8'));
  let [x0, y0, x1, y1] = [Infinity, Infinity, -Infinity, -Infinity];
  for (const p of logo.paths) {
    const [a, b, c, d] = svgPathBbox(p.d);
    x0 = Math.min(x0, a); y0 = Math.min(y0, b); x1 = Math.max(x1, c); y1 = Math.max(y1, d);
  }
  const r = (n) => +n.toFixed(3);
  logos[logo.key] = {
    name: logo.name,
    vb: [r(x0), r(y0), r(x1 - x0), r(y1 - y0)],
    paths: logo.paths.map((p) => (p.fillRule === 'evenodd' ? [p.d, 1] : [p.d])),
  };
  credits.push(`${logo.name}: ${logo.license}${logo.source ? ` — ${logo.source}` : ''}${logo.trademark ? ` (trademark of ${logo.trademark})` : ''}`);
}

writeFileSync(join(root, 'src', 'logos.js'),
  `// Generated by scripts/build-logos.mjs from data/logos/*.json — do not edit by hand.\n` +
  `// Brand logos are trademarks of their owners, used here only to identify the\n` +
  `// equipment a photo was taken with. Sources and licenses:\n` +
  credits.map((c) => `//   ${c}`).join('\n') + '\n' +
  `// Entry: { name, vb: [x, y, w, h], paths: [[d, evenodd?]] }\n` +
  `export const LOGOS = ${JSON.stringify(logos)};\n`);
console.log(`Wrote src/logos.js with ${Object.keys(logos).length} logos.`);
