// Compiles data/cameras/*.json into src/cameras.js, the compact camera
// database the app bundles. Run with: npm run cameras
//
// Each JSON file: { brand, exifMakes, cameras: [{ model, names, format,
// sensorMm: [w, h], crop, brand? }], rules: [{ pattern, format, sensorMm,
// crop, brand? }] }. Crop factors are recomputed from the sensor size
// (43.27 mm full-frame diagonal) so the data can't drift out of sync.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { prettyMake } from '../src/exif.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = join(root, 'data', 'cameras');
const FULL_FRAME_DIAGONAL = 43.27; // hypot(36, 24), rounded as camera makers and the sources use it

// Full-frame sensors range 35.6–36.0 mm wide; treat them all as exactly 1×
// so a 55mm lens stays "55mm", as cameras themselves report it.
const cropOf = ([w, h]) => {
  const c = FULL_FRAME_DIAGONAL / Math.hypot(w, h);
  return Math.abs(c - 1) <= 0.03 ? 1 : +c.toFixed(2);
};
const brands = new Map(); // brand → { cameras: Map(model → entry), rules: [] }
const warnings = [];
const notes = []; // broad rules overlapping listed models: harmless, exact models win

for (const file of readdirSync(dataDir).filter((f) => f.endsWith('.json')).sort()) {
  const data = JSON.parse(readFileSync(join(dataDir, file), 'utf8'));
  const bucket = (brand) => {
    if (!brands.has(brand)) brands.set(brand, { cameras: new Map(), rules: [] });
    return brands.get(brand);
  };
  // Brands are stored under the app's display name (prettyMake), which is
  // also how lookups find them: "Panasonic" → "LUMIX", "OLYMPUS" → "OM SYSTEM".
  const brandFor = (e) => {
    const raw = e.brand || (data.brand.includes('/') ? null : data.brand);
    return raw ? prettyMake(raw, e.model || '') : null;
  };

  for (const cam of data.cameras || []) {
    const brand = brandFor(cam);
    const [w, h] = cam.sensorMm || [];
    if (!brand || !cam.model || !(w > 0 && h > 0)) { warnings.push(`${file}: skipped ${JSON.stringify(cam).slice(0, 120)}`); continue; }
    const crop = cropOf([w, h]);
    if (cam.crop && Math.abs(cam.crop - crop) > 0.035) warnings.push(`${file}: ${cam.model} crop ${cam.crop} ≠ computed ${crop}`);
    const b = bucket(brand);
    const prev = b.cameras.get(cam.model);
    if (prev && Math.abs(prev.crop - crop) > 0.02) warnings.push(`${file}: duplicate ${cam.model} with different sensors (${prev.crop} vs ${crop}); keeping first`);
    if (prev) { prev.names = [...new Set([...prev.names, ...(cam.names || [])])]; continue; }
    b.cameras.set(cam.model, {
      model: cam.model,
      names: [...new Set((cam.names || []).filter((n) => n && n !== cam.model))],
      format: cam.format, w: +w, h: +h, crop,
    });
  }

  for (const rule of data.rules || []) {
    const brand = brandFor(rule);
    const [w, h] = rule.sensorMm || [];
    try { new RegExp(rule.pattern, 'i'); } catch { warnings.push(`${file}: bad regex ${rule.pattern}`); continue; }
    if (!brand || !(w > 0 && h > 0)) { warnings.push(`${file}: skipped rule ${rule.pattern}`); continue; }
    bucket(brand).rules.push({ pattern: rule.pattern, format: rule.format, w: +w, h: +h, crop: cropOf([w, h]) });
  }
}

// Exact models always win over rules at lookup time; also make sure no rule
// contradicts a listed model of the same brand (a sign of a sloppy pattern).
for (const [brand, b] of brands) {
  for (const rule of b.rules) {
    const re = new RegExp(rule.pattern, 'i');
    const clashes = [...b.cameras.values()].filter((c) => re.test(c.model) && Math.abs(c.crop - rule.crop) > 0.15);
    if (clashes.length) notes.push(`${brand}: rule /${rule.pattern}/ (${rule.crop}) also matches ${clashes.slice(0, 4).map((c) => `${c.model} (${c.crop})`).join(', ')}${clashes.length > 4 ? '…' : ''}`);
  }
}

// Lookups take the first matching rule, so specific patterns go before broad
// catch-alls ("PowerShot G1 X Mark II" before "PowerShot G1 X" before "PowerShot").
const specificity = (p) => p.replace(/\\.|\(\?:|[()?*+^$|]/g, '').length;
for (const b of brands.values()) b.rules.sort((x, y) => specificity(y.pattern) - specificity(x.pattern));

const out = [...brands].sort(([a], [b]) => a.localeCompare(b)).map(([brand, b]) => [
  brand,
  [...b.cameras.values()].map((c) => [c.model, c.names, c.format, c.w, c.h, c.crop]),
  b.rules.map((r) => [r.pattern, r.format, r.w, r.h, r.crop]),
]);

const count = out.reduce((n, [, cams]) => n + cams.length, 0);
const ruleCount = out.reduce((n, [, , rules]) => n + rules.length, 0);
writeFileSync(join(root, 'src', 'cameras.js'),
  `// Generated by scripts/build-cameras.mjs from data/cameras/*.json — do not edit by hand.\n` +
  `// ${count} cameras, ${ruleCount} product-line rules.\n` +
  `// Row: [EXIF model, aliases, sensor format, width mm, height mm, crop factor]\n` +
  `export const CAMERA_DB = ${JSON.stringify(out)};\n`);

console.log(`Wrote src/cameras.js: ${count} cameras, ${ruleCount} rules across ${out.length} brands.`);
if (notes.length) console.log(`${notes.length} broad rule(s) overlap listed models (exact matches take priority).`);
if (warnings.length) console.log(`\n${warnings.length} warning(s):\n` + warnings.map((w) => `  - ${w}`).join('\n'));
